Eppie-io/Eppie-CLI

src/Eppie.CLI/Eppie.CLI.sln
src/Eppie.CLI/Eppie.CLI/Eppie.CLI.csproj
src/Eppie.CLI/Eppie.CLI/Program.cs

The warning level is maximum;
clear up .cs files;

Change WarningLevel;

---

.github/workflows/build-and-test.yml

workflow file runs-on macos, ubuntu, windows

Build on macos, ubuntu, windows

---

src/Eppie.CLI/Eppie.CLI/Eppie.CLI.csproj
src/Eppie.CLI/Eppie.CLI/Menu/Actions.cs
src/Eppie.CLI/Eppie.CLI/Menu/MainMenu.cs
src/Eppie.CLI/Eppie.CLI/Resources/Program.resx
src/Eppie.CLI/Eppie.CLI/Services/Application.cs
src/Eppie.CLI/Eppie.CLI/Services/ApplicationLoop.cs
src/Eppie.CLI/Eppie.CLI/Services/CoreProvider.cs
src/Eppie.CLI/Eppie.CLI/Services/ResourceLoader.cs
src/Eppie.CLI/Eppie.CLI/appsettings.Development.json
src/Eppie.CLI/Eppie.CLI/appsettings.json

add Serilog Filter to appsettings.json, appsettings.Development.json change Console output

add Serilog.Expressions

---

.github/configs/fluidattacks_config.yaml
.github/workflows/fluidattacks.yml
tools/fluidattacks/config.yaml

- move config file
- save result file

Fix fluidattacks GitHub workflow

---

src/Eppie.CLI/Eppie.CLI/Eppie.CLI.csproj
src/Eppie.CLI/Eppie.CLI/Menu/Actions.cs
src/Eppie.CLI/Eppie.CLI/Menu/MainMenu.cs
src/Eppie.CLI/Eppie.CLI/Program.cs
src/Eppie.CLI/Eppie.CLI/Services/Application.cs
src/Eppie.CLI/Eppie.CLI/Services/ApplicationLoop.cs
src/Eppie.CLI/Eppie.CLI/Tools/LoggerExtension.cs
src/Eppie.CLI/Eppie.CLI/appsettings.Development.json

- add Logger extension
- add Default logger

Logger extension

---

src/Eppie.CLI/Eppie.CLI/Menu/Actions.cs
src/Eppie.CLI/Eppie.CLI/Menu/MainMenu.cs
src/Eppie.CLI/Eppie.CLI/Menu/MenuCommand.cs
src/Eppie.CLI/Eppie.CLI/Resources/Program.resx
src/Eppie.CLI/Eppie.CLI/Services/Application.cs
src/Eppie.CLI/Eppie.CLI/Services/ResourceLoader.cs

- add 'add-account' command
- add 'list-accounts' command

Account commands

---

src/Eppie.CLI/Eppie.CLI/Menu/Actions.cs
src/Eppie.CLI/Eppie.CLI/Menu/MainMenu.cs
src/Eppie.CLI/Eppie.CLI/Resources/Program.resx
src/Eppie.CLI/Eppie.CLI/Services/Application.cs
src/Eppie.CLI/Eppie.CLI/Services/ResourceLoader.cs

- added some help descriptions
- added reset confirmation
- changed some string resources

change menu commands

---

.github/workflows/build-and-test.yml
.github/workflows/publish.yml
src/Eppie.CLI/Eppie.CLI/Eppie.CLI.csproj
src/Eppie.CLI/Eppie.CLI/Menu/Actions.cs
src/Eppie.CLI/Eppie.CLI/Services/CoreProvider.cs
src/Eppie.CLI/Eppie.CLI/Services/ResourceLoader.cs

- change dotnet-version in github workflows
- change TargetFramework to 'net8.0'
- added primary constructors

TargetFramework 'net8.0' 

---

src/Eppie.CLI/Eppie.CLI/Eppie.CLI.csproj
src/Eppie.CLI/Eppie.CLI/Menu/Actions.cs
src/Eppie.CLI/Eppie.CLI/Options/AuthorizationOptions.cs
src/Eppie.CLI/Eppie.CLI/Services/Application.cs
src/Eppie.CLI/Eppie.CLI/Services/AuthorizationProvider.cs
src/Eppie.CLI/Eppie.CLI/Services/CoreProvider.cs
src/Eppie.CLI/Eppie.CLI/Services/TokenResolver.cs

Update gitmodules/TuviCore to 3653c90;
Add ITokenResolver implementation;
Add Connection test;
Fix Outlook authorization.

OAuth2 authorization

---

.gitmodules

- replaced absolute URLs with relative ones

Change .gitmodules

---

README.md
docs/Register the application.md

'Gmail and Microsoft Outlook OAuth2' readme

---

src/Eppie.CLI/Eppie.CLI/Eppie.CLI.csproj

- new version of the 'Finebits.Authorization.*' nuget packages

Update: Nuget packages

---

.github/workflows/publish.yml

- 'azure/trusted-signing-action' action was added
- 'actions/checkout', 'actions/setup-dotnet', 'actions/upload-artifact', 'actions/download-artifact' versions were changed

Update: 'publish.yml' github workflow

---

.github/workflows/publish.yml

- Fixed Azure secrets check condition

fix: Trusted signing on publication

---

src/Eppie.CLI/Eppie.CLI/Options/AuthorizationOptions.cs
src/Eppie.CLI/Eppie.CLI/Services/Application.cs
src/Eppie.CLI/Eppie.CLI/appsettings.json

- File logging is disabled in production mode
- Hid confidential information from logging
- Changed default logging level to errors in production mode

fix: Logging in production mode

---

src/Eppie.CLI/Eppie.CLI/Common/MailServer.cs
src/Eppie.CLI/Eppie.CLI/Menu/Actions.cs
src/Eppie.CLI/Eppie.CLI/Options/MailOptions.cs
src/Eppie.CLI/Eppie.CLI/Program.cs
src/Eppie.CLI/Eppie.CLI/Resources/Program.resx
src/Eppie.CLI/Eppie.CLI/Services/Application.cs
src/Eppie.CLI/Eppie.CLI/Services/AuthorizationProvider.cs
src/Eppie.CLI/Eppie.CLI/Services/ResourceLoader.cs
src/Eppie.CLI/Eppie.CLI/Services/TokenRefresher.cs
src/Eppie.CLI/Eppie.CLI/appsettings.json

- Added mail options to json settings
- Renamed MailService to MailServer
- Added several string resources

feat: Default addresses for mail servers

---

.github/pull_request_template.md

Added PR template file.
Eppie-io/Eppie-CLI#10

feat: GitHub PullRequest Template

---

.github/workflows/build-and-test.yml
.github/workflows/publish.yml

Update the github-action versions in the CI YAML scripts
None

ci(deps): update 'finebits' github actions

---

README.md

- Format the badge URLs
-  Add CodeQL workflow badge
N/A

docs: add codeql badge

---

.gitmodules
src/Eppie.CLI/.editorconfig
src/Eppie.CLI/Eppie.CLI.sln

- Update submodules
- Remove unused submodules
- Fix projects paths
- Disable rule **CA1848: Use the LoggerMessage delegates**
N/A

build(deps): modify submodules

---

src/Eppie.CLI/Eppie.CLI/Eppie.CLI.csproj
src/Eppie.CLI/Eppie.CLI/Menu/Actions.cs
src/Eppie.CLI/Eppie.CLI/Options/AuthorizationOptions.cs
src/Eppie.CLI/Eppie.CLI/Services/TokenRefresher.cs
src/Eppie.CLI/Eppie.CLI/Tools/CredentialExtension.cs

Read outlook email address from `id_token`
N/A

fix: fix outlook email reading

---

src/Eppie.CLI/Eppie.CLI/Menu/Actions.cs

Fix reading profile via API
N/A

fix: fix profile reading

---

.github/workflows/publish.yml

Add trusted-signing option to **publish.yml** workflow
N/A

ci: add trusted-signing option

---

src/Eppie.CLI/Eppie.CLI/Menu/Actions.cs

Use collection expression for fluent.
N/A

style: collection expression

---

.github/workflows/build-and-test.yml
.github/workflows/publish.yml

Updates `finebits/github-actions` from 2.0.0 to 3.0.0
N/A

build: bump github action version

---

.github/workflows/publish.yml
publish/config.json
publish/config.options-off.json
publish/config.options-on.json
publish/config.trim-off.json

- Bump github action version
- Modify `find-out-version` to `assign-version` action
N/A

ci: update publish workflow

---

src/Eppie.CLI/Eppie.CLI/Menu/Actions.cs
src/Eppie.CLI/Eppie.CLI/Services/Application.cs

fix: CredentialsProvider

---

src/Eppie.CLI/Eppie.CLI/Services/Application.cs

Read password from stdin.
- Eppie-io/Eppie-CLI#387

fix: read password from stdin

---

src/Eppie.CLI/Eppie.CLI.sln
src/Eppie.CLI/Eppie.CLI/Menu/Actions.cs

build: update gitmodules

---

src/Eppie.CLI/Eppie.CLI/Menu/Actions.cs

Fix CreateDecentralizedAddress call.
N/A

build: fix CreateDecentralizedAddress call

---

src/Eppie.CLI/Eppie.CLI/Eppie.CLI.csproj
src/Eppie.CLI/Eppie.CLI/Logging/HashTransformOperator.cs
src/Eppie.CLI/Eppie.CLI/Program.cs

* Implement log masking with sensitive data protection
* Fix namespace from Eppie.App.Shared.Logging to Eppie.CLI.Shared.Logging
* Fix PR check failures: improve code quality, namespace, and documentation
* Remove temporary dotnet-install.sh file from repository
* Address code review feedback: remove dotnet-install.sh from gitignore and use 'is null' pattern
N/A

feat: add log masking for sensitive data protection
